### ISSUE TITLE
Carousel AggregateException when added to Tab control

### ISSUE THREAD

**Issue by dmatter98** [chanan/BlazorStrap#260] opened 2020-01-21 14:11 UTC
**VERSION**
1.1.101 (BOS)

**ISSUE:**
When adding a Carousel to the BSTabContent region the carousel is throwing an exception.

**EXCEPTION**
[2020-01-21T14:06:44.240Z] Error: System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))

 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

   at System.Collections.Generic.List`1.get_Item(Int32 index)

   at BlazorStrap.BSCarouselItemBase.OnAfterRenderAsync(Boolean firstRender)

   --- End of inner exception stack trace ---

**RECREATE:**
1. Add multiple BSTabs to BSTabList of a BSTabGroup.
2. Add a carousel control to one of the BSTab's, BSTabContent regions.
2.1. When added to an initially selected tab (or default selected tab), you will need to click a subsequent tab and then return to the tab containing the Carousel.
2.2. When added to a subsequent tab (not initially selected), select that tab.

**UPDATE**
This appears to be related to BSTabGroup Events. When this event is fired the aggregate exception occurs. When removing events it does not.
<BSTabGroup ShowEvent="@Show" HiddenEvent="@Hidden" HideEvent="@Hide" ShownEvent="@Shown">

```
    private void Shown(BSTabEvent e)
    {
        Console.WriteLine($"Shown  -> Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
```

**Comment by MasterSkriptor** [comment] 2020-05-03 14:12
@chanan @jbomhold3 This issue is a duplicate of #270.

**Comment by timbze** [comment] 2020-05-07 21:10
@MasterSkriptor except that the error in issue 270 occurs also without any event attached. It may well be related to the same thing though.

**Closed** 2021-12-12 13:14 UTC
Labels: bug
