### ISSUE TITLE
Dropdown Close on Escape (Fixed now) or Click outside element (Still pending)

### ISSUE THREAD

**Issue by vertonghenb** [chanan/BlazorStrap#7] opened 2018-06-09 21:42 UTC
Any idea's how we can tackle the issue when a dropdown is open and we want to close it based on a random click or escape key press?

**Comment by chanan** [comment] 2018-06-09 23:13
Yes, that will be possible with Blazor 0.4.0 update. The problem is that BlazorStrap doesnt work with Blazor 0.4.0: https://github.com/aspnet/Blazor/issues/954 <--- once I either find a workaround or that issue is fixed, I will add Escape key closing dropdowns and modals.

**Comment by vertonghenb** [comment] 2018-06-09 23:19
We'll I've been looking into the escape key and that should be relatively easy. However I was thinking to add the `onfocusout` to the element but it currently doesn't sent the sender or target that triggered the event. Therefore it will always trigger the onfocusevent (hiding the dropdown) before any action on the children can be triggered or am I missing something here?

**Comment by chanan** [comment] 2018-06-09 23:21
Most likely won't be able to fix it without updating to Blazor 0.4.0, but if you add a code snippet to this issue, when I finally can update Blazor, I will make sure your use case works as well.

**Comment by vertonghenb** [comment] 2018-06-09 23:31
Here's a quick look at the Dropdown component for 0.4.0

```
@inherits BootstrapComponentBase

<DynamicElement Attributes="@UnknownParameters" TagName="div" class="@classname" onkeydown=@CloseOnEscape onfocusout=@CloseOnFocusOut>
    @ChildContent
</DynamicElement>

@functions {
    string classname
    {
        get
        {
            var open = IsOpen ? "show" : null;
            var baseclass = IsGroup ? "btn-group" : "dropdown";
            var direction = DropdownDirection != DropdownDirection.Down ? DropdownDirection.ToDescriptionString() : null;
            return $"{baseclass} {direction} {open} {Class}";
        }
    }
    [Parameter] private DropdownDirection DropdownDirection { get; set; } = DropdownDirection.Down;
    [Parameter] private bool IsOpen { get; set; }
    [Parameter] private bool IsGroup { get; set; }
    [Parameter] private string Class { get; set; }
    [Parameter] private RenderFragment ChildContent { get; set; }
    private void CloseOnEscape(UIKeyboardEventArgs ev)
    {
        if (ev.Key == "Escape")
            IsOpen = false;
    }
    private void CloseOnFocusOut(UIFocusEventArgs ev)
    {
        IsOpen = false;
        // Issue is here... UIFocusEventArgs doesn't have a sender...
        // Therefore we cannot check if it's a child of the dropdown that's being focussed.
        // And will close the dropdown before the child action is done.
       // OnBlur has the  same issue.
    }
}
```

**Comment by simonpbond** [comment] 2018-11-29 07:42
Hi all, any update on this or how to overcome it? I am also trying to implement similar functionality.
Is the only way through JS Interop?

**Comment by BlackFenix2** [comment] 2019-05-29 13:25
We might of passively resolved since Blazor updated from experimental to preview. I will double-check my fork and see if i can replicate the problem.

**Comment by jbomhold3** [comment] 2019-07-05 09:20
Most of this enchantment has already been addressed. I'll add the escape key binding in a pr tomarrow

**Comment by chanan** [comment] 2019-07-05 14:12
A fix by @jbomhold3 now lets dropdowns close on Escape key in 1.0.0-preview6-15

**Comment by jbomhold3** [comment] 2019-07-05 17:27
Might be able to do this via a simple lost focus on the parent so downtown or navitem

**Comment by jbomhold3** [comment] 2019-07-05 17:35
Blazor supports onfocusout now. This will be easy to address

**Comment by chanan** [comment] 2019-07-13 00:47
@jbomhold3 Isn't this closed now? I can click outside of a dropdown and it closes

**Closed** 2019-07-15 21:45 UTC
Labels: enhancement

**Comment by howardgod** [comment] 2019-07-18 11:10
For general dropdown button, it will close when out of focus. However, for "DropDownMenu", it won't.
Is there event I can use to set IsOpen = false?
