### ISSUE TITLE
Documentation not clear on how to integrate Bootstrap CSS or use themes

### ISSUE THREAD

**Issue by doxxx** [chanan/BlazorStrap#489] opened 2022-03-17 00:57 UTC
As a Blazor noob, I had a helluva time figuring out:

A) that the Bootstrap CSS was not statically integrated by installing the BlazorStrap NuGet package,
B) that I had to call `SetBootstrapCss` to dynamically load the CSS, and 
C) where/how to call `SetBootstrapCss`.

IMO, the Install docs page should at least mention that you need to either statically include the Bootstrap CSS or use the above mechanism. The SetBootstrapCss mechanism needs to be explained in more detail.

On .NET 6, using the Blazor Server project template, I had to edit MainLayout.razor to add `@inject IBlazorStrap _blazorStrap` near the top and a `@code` block at the end with the override for `OnAfterRenderAsync` as described on the Theme Switcher page.

Additionally, the Theme Switcher doesn't really explain _how_ to use the Bootswatch themes with that code. There's a nebulous string `name` parameter but no indication what that should actually contain to use one of the themes. I only just now figured out that there's an overload that takes a `Theme` enum.

**Comment by dattiphu2022** [comment] 2022-04-23 04:35
in the document about modal (the first modal and some on this page)
https://blazorstrap.io/V5/components/modal

Where is the _Footer_, _Context_ and _modal_ in `<Footer Context = "modal">`come from, please? Is that a bug?
Thanks for reading this comment!

**Comment by jbomhold3** [comment] 2022-04-23 06:44
@dattiphu2022 not it's not a bug. Footer is a renderfragment of BSModal. This keeps you form having to take a reference of the modal just to close it. Context is the automatically created generated by Blazor for templated RenderFragment's. The Context="modal" is just renaming context to modal instead. 

See https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/components#templated-components

**Comment by jbomhold3** [comment] 2022-04-23 06:54
Toggle between modals example
Does not take in the Context at all because showing the new model automatically closes the current model and opens the new one. 

While the example below would be work to close as well but not shown because of the following.
1) BSModal was one of the first components done in V5 even before the concept of Target was add. 
2) Target invokes Toggle vs Close directly.

``` html
<BSModal DataId="modalTest" IsCentered="true">
    <Header>Modal Test</Header>
    <Content>This is a test Modal</Content>
    <Footer>
        <BSButton MarginStart="Margins.Auto" Color="BSColor.Secondary" Target="modalTest">Close</BSButton>
    </Footer>
</BSModal>
```

Sidenote: Toggle between modal without needing references was one of the things that inspired the Target callback concept in the first place.

**Closed** 2022-12-06 12:28 UTC
Labels: enhancement, documentation, Bootstrap 5

**Comment by dattiphu2022** [comment] 2022-12-18 12:49
Thank you!
