### ISSUE TITLE
Collapsing class not removed

### ISSUE THREAD

**Issue by pelshen** [chanan/BlazorStrap#330] opened 2020-05-22 11:47 UTC
I'm finding that when using BSCollapse, the collapsing class is not being removed after opening or closing. I'm using v1.3.2. You can see this behaviour in your own examples on https://blazorstrap.io/collapse if you inspect any of the collapse divs, once you open it, "collapsing" never goes away. This leaves CSS on the element like overflow: hidden that isn't helpful if your design has, for example, an overhanging border.

**Comment by chanan** [comment] 2020-05-22 18:42
The problem might be even worse than not removing it. It "flickers", it gets removed and put back right away in a loop

**Comment by jbomhold3** [comment] 2020-05-23 02:21
Probably going to require a rewrite on that function. Interop is a lot better then it was when I wrote that so I should be able to do this a lot cleaner now.

**Comment by pelshen** [comment] 2020-05-28 10:12
Is there any kind of ETA on this?

**Comment by chanan** [comment] 2020-05-28 16:02
I need this for my day job... We are actually using Blazor and of course BlazorStrap at work now :)

I plan to look at it this weekend. Based on what John said above and my quick peek at it I think the issue is in the JS code somewhere here:

https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/wwwroot/blazorStrap.js#L177-L198

So hopefully it will be easy to fix...

**Comment by jbomhold3** [comment] 2020-05-28 17:58
It's the js. I was trying to track the progress of the animation far too much between blazer and the js. It's simply not needed. Just need to make that a signal toggle and report when it's finished opening or closing. Don't even statehaschanged just track what class has finished that way when one is called it shows in the right state

**Comment by chanan** [comment] 2020-05-31 15:59
I can no longer reproduce this which is weird. I tried both locally and at https://blazorstrap.io/collapse - Can you guys give a try and see if it magically got fixed there as well?

On a side note: @jbomhold3 Can you see if this is working for you. I update the docs site but it doesnt seem to get updated (or I have some weird bug somewhere). I changed MainLayout.js to use bootstrap 4.5.0 - but when I look in the head of the docs site its still 4.3.1

**Comment by jbomhold3** [comment] 2020-05-31 20:16
still seeing 4.3.1  on the docs. Can spam collapsing and it does not seem to break. did you make any changes here?

**Comment by chanan** [comment] 2020-05-31 20:18
No i didn’t change a thing...

Also can’t figure out why the docs didn’t update. One thing magically fixed another magically broke...

**Comment by pelshen** [comment] 2020-05-31 21:49
Will have a look tomorrow (during the day job ;) )

**Comment by pelshen** [comment] 2020-06-01 21:36
Sorry, today I was still seeing the issue, but didn't have time to make a simple reproduction. Might be Wednesday I get to that now. Is the only change you've made to the docs to up the Bootstrap version?

**Comment by chanan** [comment] 2020-06-01 21:38
I tired to change it to 4.5 but it seems like it didn’t “take” and it’s still on 4.3.1. I haven’t had a chance to investigate why yet

**Comment by pelshen** [comment] 2020-06-05 13:19
Sorry for the delay. Below I have simplified a collapsible panel component that I have and this should work in the default template. I've removed Parameters and hardcoded text instead, so should be able to just drop this in anywhere.

```
<div>
    <a class="justify-content-between align-items-center d-flex" @onclick="Toggle">
        <h3 class="d-flex align-items-center">
            Click here
        </h3>
    </a>
    <BSCollapse IsOpen="IsOpen">
        Test content
    </BSCollapse>
</div>

@code {
    private bool IsOpen { get; set; } = false;

    private void Toggle(MouseEventArgs e)
    {
        IsOpen = !IsOpen;
        StateHasChanged();
    }
}
```

The collapsing class just gets stuck after the first open.

**Comment by pelshen** [comment] 2020-06-09 16:41
I got around to trying the above in a fresh Blazor project from the template and I still see the behaviour with BlazorStrap v1.3.2

**Comment by chanan** [comment] 2020-06-09 16:42
Thanks for the update, we will try it out again also on a fresh project

**Comment by pelshen** [comment] 2020-06-12 13:31
This seems to also be causing a bug where if anything makes the collapsible area larger (or smaller), the height doesn't change. I think this is because the inline height style hasn't been removed and the collapsing class is still on it, so I think this is effectively the same bug.

**Comment by pelshen** [comment] 2020-06-12 14:04
I've worked out why we have seen different things. AnimationEnd(), which clears collapsing, is triggered by ontransitionend. Bootstrap has a rule in _transitions.scss
```
@media (prefers-reduced-motion: reduce) {
      transition: none;
}
```

Looking at https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion, this exists for accessibility and similar to Firefox as listed, Chrome respects the Windows 10 setting for Show animations on Windows. For some reason the client VM I'm working with had this set to off, so this CSS rule was being applied. This meant no transition and no transition means no transitionend event, so AnimationEnd() is not called. I switched the setting and now, it works as expected.

Although the severity of this is greatly reduced, this shouldn't fail to work if a user has this setting enabled (particularly given it may not be intentional or recognised to affect browsers).

**Comment by chanan** [comment] 2020-06-15 16:03
@jbomhold3 any thoughts on how we can handle this?

**Comment by MasterSkriptor** [comment] 2020-06-15 21:54
If I am understanding you correctly @pelshen this would be a bug that also affects bootstrap itself?

**Comment by pelshen** [comment] 2020-06-16 08:40
@MasterSkriptor I don't believe so. In [BSCollapse.razor](https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap/Components/Layout/BSCollapse.razor) `AnimationEnd` (the method that ends the collapse) is set as the callback to `ontransitionend` so it is this library deciding to do this only when a transition finishes. If I switch the option in Windows and look at Bootstrap's own examples, the collapse still works okay. In fact, you can change the collapsing class' transition to none in dev tools, and see the collapse body just appear and disappear, collapsing is not left behind.

**Comment by chanan** [comment] 2020-06-16 13:36
I took a look at react-bootstrap to see how it is handled there. The class: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Collapse.js calls another library called `react-transition-group`: https://github.com/reactjs/react-transition-group/blob/master/src/Transition.js

So I think we have two choices (as well as other ones of course):

1. We could copy the logic from that class into ours
2. Similar to what we did with Popper.js we could embed that library into our code and use it directly (Might be difficult since the code is meant for react)
3. Some other solution... ?

**Comment by MasterSkriptor** [comment] 2020-06-17 12:26
I haven't tested it, but we may be able to add this to our own css to override Bootstraps implementation?

@media screen and
  (prefers-reduced-motion: reduce){
  * {
    animation-duration: 0.001ms !important;
    animation-iteration-count: 1 !important; 
    transition-duration: 0.001ms !important;

  }
}

It would allow the animations to run but happen almost instantly.

See https://davidwalsh.name/prefers-reduced-motion

**Closed** 2020-06-17 23:28 UTC
Labels: Important, bug

**Comment by wocar** [comment] 2020-07-01 21:52
is this released yet? My accordion flickers. Thank you!

**Comment by pelshen** [comment] 2020-07-20 11:20
@wocar this is marked for the 1.3.3 release, which hasn't been released yet. Do we have an ETA on 1.3.3? @chanan @jbomhold3
