### ISSUE TITLE
BSNavItem active classes not switched until additional click event

### ISSUE THREAD

**Issue by noahc3** [chanan/BlazorStrap#164] opened 2019-08-17 17:59 UTC
Following up on https://github.com/chanan/BlazorStrap/issues/147 now that I've had a chance to try it.

In my nav bar, when I click on a link, the active class is not applied to the nav-item correctly until I click again anywhere in the window. It is applied to the nav-link correctly, but this is not responsible for the text color.

GIF of the issue: ![](https://puu.sh/E6lDM/9e8da3e596.gif)

You can see the highlighted nav-link element gets active applied correctly, but the parent nav-item does not until I click again.

Using v1.0.0-preview8-01

**Comment by jbomhold3** [comment] 2019-08-17 18:27
Looks like we didn't call statehaschanged . should be able to work around this until fixed with an oninit  statehaschanged..

**Comment by jbomhold3** [comment] 2019-08-19 21:17
Exact error is we are calling statehaschanged on the child and not the parent. Will be fixed in next release

**Comment by jbomhold3** [comment] 2019-08-29 01:58
@noahc3  Can you verify the issue is now resolved for you.

**Closed** 2019-09-05 02:21 UTC
Labels: bug
