### ISSUE TITLE
BSModal and EditForm

### ISSUE THREAD

**Issue by siatki** [chanan/BlazorStrap#511] opened 2022-04-25 19:42 UTC
Hi, I updated BlazorStrap to v5 and now I have some problem with using BSModal with EditForm (or BSForm). 

EditForm inside BSModal is not alloved -> "Unrecognized child content inside component BSModal".

When EditForm is outside BSModal then there is a problem with opening the modal. I get following error:

_Microsoft.JSInterop.JSException: 'Cannot read properties of null (reading 'style')
TypeError: Cannot read properties of null (reading 'style')
    at Object.PeakHeight (https://localhost:44345/_content/BlazorStrap/blazorStrap.js:346:32)_

The following code is an example to repeat the situation. The problem occurs only when I assign a new value to the EditForm model variable  (commented line in OpenModal method).

```
<EditForm Model="item" OnValidSubmit="@Update">
    <BSModal @ref="refModal">
        <Header>Head</Header>
        <Content>
            @item.ToString()
        </Content>
        <Footer Context="ctx">
            <BSButton @onclick="@(() => ctx.HideAsync())">Cancel</BSButton>
            <BSButton IsSubmit="true" Color="BSColor.Primary">Save</BSButton>
        </Footer>
    </BSModal>
</EditForm>

<BSButton @onclick="(() => OpenModal(new object()))">Open modal</BSButton>

@code {
    BSModal refModal;
    private object item = new object();
    private async void OpenModal(Object _item)
    {
        item = _item; //this line is causing the problem
        await refModal.ShowAsync();
    }
    private async Task Update()
    {
    }
}
```

In BlazorStrap v1 my EditForm component was nested inside BSModal and everything worked. Please help to solve the problem.

**Comment by jbomhold3** [comment] 2022-04-25 21:33
The example you provided is disposing BSModal and rebuilding it completely. Meaning it needs to draw again before calling Show.

Will require a little bit of thinking to solve this fully going forward.
This while not graceful does work.

``` C#
@code {
    BSModal refModal;
    private bool Show;
    private object item = new object();
    private async void OpenModal(object _item)
    {
        item = _item; //this line is causing the problem
        Show = true ;
    }
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if(Show)
        {
            Show = false;
            await refModal.ShowAsync();
        }
    }
    private async Task Update()
    {
    }
}
```

**Comment by jbomhold3** [comment] 2022-04-25 22:03
I think the best solution to the issue is will be to add BSHeader,BSContent, BSFooter Components. We can infer the needed class by presents on the cascading value.

Witch seems like your indented use anyways. 

This would make the code more Stright forward incases like this where you need different nested content.
A clear benefit is once inside the BSModel EditForm would not be able to dispose anything as they invoke. 

``` html
<BSModal @ref="refModal">
     <EditForm Model="item" OnValidSubmit="@Update">
        <BSHeader>Head</BSHeader>
        <BSContent>
            @item.ToString()
        </BSContent>
        <BSFooter Context="ctx">
            <BSButton @onclick="@(() => ctx.HideAsync())">Cancel</BSButton>
            <BSButton IsSubmit="true" Color="BSColor.Primary">Save</BSButton>
        </BSFooter>
    </EditForm>
</BSModal>
```

**Comment by jbomhold3** [comment] 2022-04-25 22:10
This will be in attention to the existing way of doing things not a replacement. For cases where the templated components don't work.

**Comment by jbomhold3** [comment] 2022-04-26 00:02
Quick fix is almost complete. Will post a package. Also will be tossing a friendly exception if your trying to do something that blows up the ref for now. Will readdress in next minor version since will require some design changes to 6 components to ensure this can never happen.

**Comment by jbomhold3** [comment] 2022-04-26 01:14
Addressed in https://www.nuget.org/packages/BlazorStrap/5.0.105.4252022

``` html
<BSModal @ref="refModal">
     <EditForm Model="item" OnValidSubmit="@Update">
        <BSModalHeader>Head</BSModalHeader>
        <BSModalContent>
            @item.ToString()
        </BSModalContent>
        <BSModalFooter>
            <BSButton @onclick="@(() => refModal.HideAsync())">Cancel</BSButton>
            <BSButton IsSubmit="true" Color="BSColor.Primary">Save</BSButton>
        </BSModalFooter>
    </EditForm>
</BSModal>
```

**Comment by jbomhold3** [comment] 2022-04-26 02:57
Deleted all my way over thinking messages without fully reading sorry about that.

**Closed** 2022-04-26 02:57 UTC
Labels: Important, Planning, Bootstrap 5
