### ISSUE TITLE
How to maintain state in dynamic tabs

### ISSUE THREAD

**Issue by jhcorey** [chanan/BlazorStrap#407] opened 2020-11-10 15:12 UTC
I have tabs bound to a list.  When I switch tabs and then return the content from my own components is lost.  In my example here, the tab content includes (1) a BSBasicInput and (2) a component called StrategyComp, which also has a BSBasicInput.  When I switch among tabs the value within the BSBasicInput shown here is maintained, but the contents of StrategyComp is lost and the input is blank.  I have tried using @key in different places.

We previously implemented this functionality in Angular Bootstrap, and adding the [destroyOnHide]="false" attribute took care of this issue.

    <BSTabGroup @ref="TabGroup" ShowEvent="@Show" HiddenEvent="@Hidden" HideEvent="@Hide" ShownEvent="@Shown">
        <BSTabList>
            @foreach (var tab in _tabList)
            {
                <BSTab @key="tab">
                    <BSTabLabel>@tab.Label <strong @onclick="() => RemoveTab(tab.Id)">X</strong></BSTabLabel>
                    <BSTabContent @key="tab">
                           @if (tab.TabOption == TabOption.Create)
                            {
                                <BSBasicForm>
                                    <BSFormGroup>
                                        <BSBasicInput InputType="InputType.Text" placeholder="First name" @bind-Value="FirstName" />
                                        <StrategyComp @key="tab" @bind-Value="strategyComp"></StrategyComp>
                                    </BSFormGroup>
                                </BSBasicForm>
                            }
                           @if (tab.TabOption == TabOption.View)
                            {
                               <ViewComp @key="tab" @bind-Value="viewComp"></ViewComp>
                           }
                     </BSTabContent>
                </BSTab>
            }
        </BSTabList>
        <BSTabSelectedContent />
    </BSTabGroup>

**Comment by beccajohnson17** [comment] 2020-11-19 06:01
I am also having this issue. Was this something resolved in the latest version? Currently on 1.3.3 and can't update because of dependency issues.

**Comment by chanan** [comment] 2020-11-19 21:45
Can someone create a reproduction that we can run?

**Comment by jhcorey** [comment] 2020-11-19 22:29
Here is (1) a component containing an Input, and (2) a page which has both an Input and the component within the tab content.  When I run this there will be inputs for First Name and Second Name.  Only First Name maintains the content when I switch back and forth between tabs.
Thanks!

**Contents of component SimpleComp.razor:**

<BSBasicForm>
    <BSFormGroup>
<BSBasicInput InputType="InputType.Text" placeholder="Second name" @bind-Value="SecondName" />
</BSFormGroup>
    </BSBasicForm>
@code {
    private string SecondName;
}

**Page with Tabs:**


@page "/tabExample"
<BSTabGroup>
    <BSTabList>

        <BSTab>
            <BSTabLabel>Tab 1</BSTabLabel>
            <BSTabContent>
                <BSBasicInput InputType="InputType.Text" placeholder="First name" @bind-Value="FirstName" />
                <SimpleComp></SimpleComp>

            </BSTabContent>
        </BSTab>
        <BSTab>
            <BSTabLabel>Tab 2</BSTabLabel>
            <BSTabContent>Tab 2 Static Content.</BSTabContent>
        </BSTab>
    </BSTabList>
    <BSTabSelectedContent />
</BSTabGroup>

@code {
    private string FirstName;
}

**Comment by jhcorey** [comment] 2020-11-19 22:31
Sorry, somehow when I posted it did not include the html for the SimpleComp component.  I'll try again here:
<BSBasicForm>
    <BSFormGroup>
<BSBasicInput InputType="InputType.Text" placeholder="Second name" @bind-Value="SecondName" />
</BSFormGroup>
    </BSBasicForm>
@code {
    private string SecondName;
}

**Comment by jhcorey** [comment] 2020-11-19 22:33
This is strange,  I'm unable to include BSBasicForm when I paste code.  In SimpleComp I have the BasicInput in a BSBasicForm and BSFormGroup, but I've tried many variations on this.

**Comment by beccajohnson17** [comment] 2020-11-19 22:49
I know there was a similar issue on this opened before, where inserting <BSTab @key="tab"> resolved the issue, but it didn't seem to work for me.

**Comment by jbomhold3** [comment] 2020-12-01 20:53
Easiest solution for this would be to have a shared model. Blazor is blowing away the state of the render fragment

**Comment by jbomhold3** [comment] 2020-12-01 21:06
**SimpleModel.cs** 
``` C#
   public class SimpleModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
```
-------------
**TabComp**
``` html
@page "/samples/issue407"

<BSTabGroup ShowEvent="@Show" HiddenEvent="@Hidden" HideEvent="@Hide" ShownEvent="@Shown">
    <BSTabList>
        <BSTab>
            <BSTabLabel>Tab 1</BSTabLabel>
            <BSTabContent>
                <BSBasicInput InputType="InputType.Text" placeholder="First name" @bind-Value="Model.FirstName" />
                <SimpleComp Model="Model"></SimpleComp>

            </BSTabContent>
        </BSTab>
        <BSTab>
            <BSTabLabel>Tab 2</BSTabLabel>
            <BSTabContent>Tab 2 Static Content.</BSTabContent>
        </BSTab>
    </BSTabList>
    <BSTabSelectedContent />
</BSTabGroup>
```
``` C#
@code {
    SimpleModel Model = new SimpleModel();
    private void Show(BSTabEvent e)
    {
        Console.WriteLine($"Show   -> Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
    }
    private void Shown(BSTabEvent e)
    {
        Console.WriteLine($"Shown  -> Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
    }
    private void Hide(BSTabEvent e)
    {
        Console.WriteLine($"Hide   ->  Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
    }
    private void Hidden(BSTabEvent e)
    {
        Console.WriteLine($"Hidden -> Activated: {e.Activated?.Id.ToString()} , Deactivated: {e.Deactivated?.Id.ToString()}");
    }
}
```
---------
**SimpleComp**
``` html
<BSBasicInput InputType="InputType.Text" placeholder="Last name" @bind-Value="Model.LastName" />
```
``` C#
@code {  
    [Parameter] public SimpleModel Model { get; set; }  
}
```

**Comment by jhcorey** [comment] 2020-12-01 21:16
Thanks for the quick reply!  I'll give it a try

**Closed** 2021-12-12 13:14 UTC
